# Industry 4.0 의 중심, AI - ML&DL

<div align='right'><font size=2 color='gray'>Machine Learning & Deep Learning with TensorFlow @ <font color='blue'><a href='https://www.facebook.com/jskim.kr'>FB / jskim.kr</a></font>, 김진수</font></div>
<hr>

## Tensorflow Programming Model

### 1. 텐서플로우 2.0 환경에서 1.x 코드 실행하기
> https://lv99.tistory.com/31
> - 코드 변환에 아직 어려움이 있으신 분이 있다면, 아래와 같은 방법으로 여전히 1.x 버전의 코드를 실행할 수 있습니다.
> - tensorflow가 2.0으로 올라가면서, 더이상 Session 모듈을 지원하지 않게 되었습니다.
> - 설치 오류가 아닙니다. 아래와 같이 코드를 작성하면 Session 사용 가능 합니다.
> <br/>
> <br/> import tensorflow.compat.v1 as tf
> <br/> tf.disable_v2_behavior()
> <br/><br/>
> - <b>하지만</b> 실행 결과창에 끊임없이 경고 메시지가 뜬다는...ㅠㅠ;

> <br/> import tensorflow.compat.v1 as tf
> <br/> tf.disable_v2_behavior()

### 2. 텐서플로우 1.x 코드를 2.0 코드로 업그레이드하기
>  
> - 2.0으로 바꾸시려면 업그레이드 스크립트를 사용하고, 자동변환되지 않는 부분에 대해서 직접 수정을 거쳐야합니다.
> - 혹은, 차근 차근 직접 바꿔나가는 방법도 있습니다. (이게 더 안정적임) 이것은 다음의 링크(준비중)를 확인해주세요.

 

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

### <font color='brown'>TF01_Hello</font>

In [3]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()
# tf.compat.v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
# import tensorflow as tf

hello = tf.constant(" Hello TensorFlow!")
sess = tf.Session()

sess.run(hello)

b' Hello TensorFlow!'

### <font color='brown'>TF02_Variable</font>

In [5]:
#first_session_only_tensorflow.py

x = tf.constant(100, name='x')
y = tf.Variable(x*2, name='y')

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    print("constant x : {x} \nVariable y : {y}".format(
        x = sess.run(x), 
        y = sess.run(y)
    ))

constant x : 100 
Variable y : 200


### <font color='brown'>TF03_placeholder</font>

In [6]:
# 변수 a, b는 동적으로 지정
a = tf.placeholder("int32")
b = tf.placeholder("int32")

# multiply 함수는 입력된 정수 a와 b의 곱셈을 반환한다.
y = tf.multiply(a,b)

sess = tf.Session()

print("tf.multiply({a},{b}) : {y}".format(
    a = 20, b = 30,
    y = sess.run(y , feed_dict={a: 20, b: 30})
))

tf.multiply(20,30) : 600


### <font color='brown'>TF04_Tensorboard</font>

In [7]:
a = tf.constant(10, name="a")
b = tf.constant(20, name="b")
y = tf.Variable(a**2 + b**2, name="y")

model = tf.global_variables_initializer()

with tf.Session() as sess:
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./graph/board", sess.graph)
    sess.run(model)
    print(" constant a = {a} \n constant b = {b} \n Variable y = {y}".format(
        a = sess.run(a), 
        b = sess.run(b),
        y = sess.run(y)
    )) 

 constant a = 10 
 constant b = 20 
 Variable y = 500


In [8]:
# !tensorboard --logdir=graph/board --port=9999

### <font color='brown'>TF05_Tensor_Operation</font>

In [9]:
import numpy as np

tensor_1d = np.array([1.2, 3.4, 5.6, 7.8])
tensor_2d = np.arange(16).reshape((4,4))

In [10]:
tf_tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)

with tf.Session() as sess:
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[0]))
    print(sess.run(tf_tensor[-1]))

[1.2 3.4 5.6 7.8]
1.2
7.8


In [11]:
tf_tensor_1d = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)
tf_tensor_2d = tf.convert_to_tensor(tensor_2d, dtype=tf.float64)
sess = tf.Session()

In [12]:
sess.run(tf_tensor_1d)

array([1.2, 3.4, 5.6, 7.8])

In [13]:
sess.run(tf_tensor_1d[0])

1.2

In [14]:
sess.run(tf_tensor_1d[2:])

array([5.6, 7.8])

In [15]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [16]:
sess.run(tf_tensor_2d[3][3])

15.0

In [17]:
sess.run(tf_tensor_2d[1:3,1:3])

array([[ 5.,  6.],
       [ 9., 10.]])

### <font color='brown'>TF06_TF1 vs TF2</font>

#### TensorFlow V1 방식
> V1에서는 node들을 모두 빌드업 해둔 다음 Session 모듈을 이용해 그래프를 실행

In [18]:
import os 

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)
node3 = tf.add(node1, node2)

sess = tf.Session()
print(sess.run(node3))


7.0


#### TensorFlow V2 방식
>  V2에서는 입력값 (input)이 들어가는 node들만 빌드업 해둔 후 그 다음 node (이 예제에서는 node3)은 미리 빌드업 해둔 게 아니라 함수로 정의해서 실행

In [19]:
# Info 로그를 필터링하려면 1, Warning 로그는 2, Error 로그는 3
import os 

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

# 앞쪽 레이어의 노드 빌드하기
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)

# 뒷쪽 레이어의 노드(즉, node3)를 함수로 정의하기
@tf.function
def forward():
    return node1+node2

# 그래프를 실행시키고 output을 확인해보기
out_a = forward()
print(out_a)

Tensor("PartitionedCall:0", shape=(), dtype=float32)


> 참조 : https://www.tensorflow.org/guide/migrate?hl=ko

In [20]:
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

@tf.function
def forward(x):
    return W * x + b

out_a = forward([1,0])
print(out_a)

Tensor("StatefulPartitionedCall:0", shape=(2, 2), dtype=float32)


<hr>
<marquee><font size=3 color='brown'>The BigpyCraft find the information to design valuable society with Technology & Craft.</font></marquee>
<div align='right'><font size=2 color='gray'> &lt; The End &gt; </font></div>